### ISSUE TITLE
ImportError: No module named 'Cython'

### ISSUE THREAD

**Issue by sraddhanjali** [shunsukeaihara/pydtw#2]
Pip install pydtw throws import error.

```
Collecting pydtw
  Downloading pydtw-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-16ffmgc7/pydtw/setup.py", line 3, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-16ffmgc7/pydtw/
```

**Comment by shunsukeaihara** [comment]
fix it on #5
